// Each component module prefixes its type names (DataTable*, Kanban*, Feed*,
// Calendar*, FormBuilder*) and its value exports are unique, so `export *` is
// collision-free and keeps this root barrel automatically in sync with every
// type each component declares — no hand-maintained list to fall out of date.
export * from "./src/datatable/index";
export * from "./src/kanban/index";
export * from "./src/feed/index";
export * from "./src/calendar/index";
export * from "./src/form/index";

export {
  ActiveFilterChips,
  AutoTag,
  AutoStatusTag,
  CollectionCount,
  CollectionFilterControl,
  CollectionSortSelect,
  CollectionToolbar,
  CrmLookupSelect,
  formatCollectionCount,
  KeyValueList,
  SectionHeader,
  Spinner,
  SPINNERS,
  SPINNER_NAMES,
  gridToBraille,
  makeGrid,
} from "./common-components";
export {
  Icon,
  ICON_NAMES,
  ICONS,
  NATIVE_ICON_NAME_LIST,
  makeIconDataUri,
  svgToIconEntry,
  AvatarStack,
  StyledText,
  makeAvatarStackDataUri,
  makeStyledTextDataUri,
  HS_DATE_DIRECTION_LABELS,
  HS_DATE_PRESETS,
  HS_FONT_FAMILY,
  HS_TEXT_COLOR,
  HS_SUBTLE_BG,
  HS_MUTED_TEXT,
  HS_NEUTRAL_CHIP,
  HS_TAG_SUBTLE_BORDER,
  HS_TAG_TEXT_COLOR,
  HS_TAG_FONT_SIZE,
  HS_TAG_LINE_HEIGHT,
  HS_TAG_PADDING_X,
  HS_TAG_PADDING_Y,
  HS_TAG_BORDER_RADIUS,
  HS_TAG_BORDER_WIDTH,
  DEFAULT_SVG_FONT_WEIGHT,
} from "./common-components";
export {
  buildActiveFilterChips,
  buildCrmSearchConfig,
  buildOptions,
  createStatusTagSortComparator,
  crmSearchResultToOption,
  CrmDataTable,
  CrmKanban,
  findOptionLabel,
  formatCurrency,
  formatCurrencyCompact,
  formatDate,
  formatDateTime,
  formatPercentage,
  getAutoTagVariant,
  getAutoStatusTagVariant,
  getEmptyFilterValue,
  getEmptyFilterValues,
  isFilterActive,
  makeCrmSearchMultiSelectField,
  makeCrmSearchSelectField,
  normalizeCrmSearchRecord,
  normalizeCrmSearchRows,
  resetFilterValues,
  resolveCrmObjectType,
  searchRows,
  filterRows,
  sumBy,
  toStableKey,
  useCrmSearchDataSource,
  useCrmSearchOptions,
} from "./utils";
export type {
  AutoTagOptions,
  AutoTagVariant,
  AutoStatusTagOptions,
  AutoStatusTagVariant,
  StatusTagSortComparatorOptions,
  CrmDataTableProps,
  CrmKanbanProps,
  CrmSearchDataSource,
  CrmSearchConfigOptions,
  CrmSearchOptionsDataSource,
  CrmSearchPagination,
  CrmSearchParams,
  QueryFilterConfig,
  ActiveFilterChip,
  FilterResetOptions,
  BuildActiveFilterChipsOptions,
} from "./utils";
export type {
  ActiveFilterChipsProps,
  AutoTagProps,
  AutoStatusTagProps,
  AvatarStackDataUriResult,
  AvatarStackItem,
  AvatarStackItemObject,
  AvatarStackProps,
  IconProps,
  IconEntry,
  IconPath,
  IconPathObject,
  IconSize,
  IconDataUriResult,
  IconDataUriOptions,
  CollectionCountProps,
  CollectionFilterControlProps,
  CollectionSortSelectProps,
  CollectionToolbarProps,
  CrmLookupSelectProps,
  DateDirectionLabels,
  DatePresetOption,
  KeyValueListItem,
  KeyValueListProps,
  SectionHeaderProps,
  SpinnerName,
  SpinnerPreset,
  SpinnerProps,
  StyledTextBackground,
  StyledTextDataUriOptions,
  StyledTextDataUriResult,
  StyledTextFormat,
  StyledTextProps,
} from "./common-components";
