// ---------------------------------------------------------------------------
// Turns scraped icon JSON into src/common-components/icons.generated.js.
//
//   1. Scrape with scripts/scrape-hs-icons.console.js (browser console).
//   2. Save the copied JSON to scripts/scraped-icons.json.
//   3. node scripts/build-icons.mjs   (or: npm run build:icons)
//
// MERGES into the existing icons.generated.js rather than replacing it, so each
// scrape batch is ADDITIVE — you can paste over scraped-icons.json with a fresh
// batch from a new browser session and never lose previously-captured icons.
// Dedupe is by name: a name present in both keeps the newly-scraped geometry.
// Pass --replace to start from scratch instead of merging.
//
// Input shape (what the scraper produces):
//   { "<data-icon-name>": { viewBox: "0 0 32 32", paths: [ "M…" | {d,fill?,fillRule?} ] } }
// Output: a deterministic, alphabetically-sorted ESM module. Same merged set
// always yields byte-identical output, so re-runs make clean diffs.
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const input = resolve(root, "scripts/scraped-icons.json");
const output = resolve(root, "src/common-components/icons.generated.js");
const replace = process.argv.includes("--replace");

if (!existsSync(input)) {
  console.error(
    `No ${input}.\nScrape icons with scripts/scrape-hs-icons.console.js, save the\nclipboard JSON to scripts/scraped-icons.json, then re-run.`
  );
  process.exit(1);
}

// Load the icons already committed to the generated module so this batch is
// additive (unless --replace). The generated object literal is itself valid
// JSON (quoted keys, string/array values), so slice it out and parse — avoids
// importing an ESM module from a CommonJS-typed package.
let existing = {};
if (!replace && existsSync(output)) {
  try {
    const src = readFileSync(output, "utf8");
    const start = src.indexOf("{");
    const end = src.lastIndexOf("}");
    if (start !== -1 && end > start) {
      existing = JSON.parse(src.slice(start, end + 1));
    }
  } catch {
    console.warn("Could not read existing icons.generated.js — starting fresh.");
  }
}

const scraped = JSON.parse(readFileSync(input, "utf8"));
const beforeCount = Object.keys(existing).length;
const newNames = Object.keys(scraped).filter((n) => !(n in existing));
// Scraped entries win on collision (freshest geometry); existing-only survive.
const raw = { ...existing, ...scraped };

const normalizePath = (p) => {
  const d = (typeof p === "string" ? p : p && p.d || "").trim();
  if (!d) return null;
  if (typeof p === "string") return d;
  const keepFill = p.fill && p.fill !== "currentColor" && p.fill !== "none";
  return {
    d,
    ...(keepFill ? { fill: p.fill } : {}),
    ...(p.fillRule ? { fillRule: p.fillRule } : {}),
  };
};

const names = Object.keys(raw).sort((a, b) => a.localeCompare(b));
let skipped = 0;
const viewBoxes = new Map(); // viewBox -> count, for the standardization audit
const body = names
  .map((name) => {
    const entry = raw[name] || {};
    const paths = (entry.paths || []).map(normalizePath).filter(Boolean);
    if (!paths.length) {
      skipped++;
      console.warn(`  skip "${name}": no usable path data`);
      return null;
    }
    const viewBox = entry.viewBox || "0 0 24 24";
    viewBoxes.set(viewBox, (viewBoxes.get(viewBox) || 0) + 1);
    const value = { viewBox, paths };
    return `  ${JSON.stringify(name)}: ${JSON.stringify(value)}`;
  })
  .filter(Boolean)
  .join(",\n");

// Standardization audit — icons render width×size into their own viewBox, so a
// mixed set still works, but a single viewBox keeps optical weight uniform.
if (viewBoxes.size > 1) {
  const breakdown = [...viewBoxes.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([vb, n]) => `${vb} (${n})`)
    .join(", ");
  console.warn(`\n⚠ mixed viewBoxes — icons may not share optical weight: ${breakdown}\n`);
}

const out =
  `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.\n` +
  `// Source: icons scraped from HubSpot's web app (see scripts/scrape-hs-icons.console.js).\n` +
  `// Keys are the original \`data-icon-name\` values. Regenerate after re-scraping.\n\n` +
  `export const GENERATED_ICONS = {\n${body}\n};\n`;

writeFileSync(output, out);
const total = names.length - skipped;
const updated = Object.keys(scraped).length - newNames.length;
console.log(
  `${total} icons total in icons.generated.js ` +
    `(+${newNames.length} new, ${updated} updated, ${beforeCount} prior)` +
    (skipped ? ` — ${skipped} skipped (no path data)` : "") +
    (replace ? " [--replace: prior set discarded]" : "")
);
